version: '3.8'

services:
  backend:
    build: ../backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/app_db
    depends_on:
      - postgres
    volumes:
      - ../backend:/app
      - /app/node_modules

  frontend:
    build: ../frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    volumes:
      - ../frontend:/app
      - /app/node_modules

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=app_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
