version: '3.8'

services:
  backend:
    build:
      context: ../backend
      dockerfile: ../infra/backend.Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ../.env
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - DATABASE_URL=${DATABASE_URL}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - postgres
      - minio
    volumes:
      - ../backend:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build: ../frontend
    ports:
      - "3000:3000"
    env_file:
      - ../.env
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    volumes:
      - ../frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=app_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:RELEASE.2024-01-01T16-36-33Z
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"  # S3 API port
      - "9001:9001"  # Console port
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data:
